#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       space-separated string is a well documented source of bugs and
#       security problems, so this is (mostly) avoided, by progressively
#       accumulating output within an unquoted scalar variable Args.
#
#       Where the equivalent could be requested via a jvm system property, we
#       use that alternative to minimize the risk of parameter breakage.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd -P "${APP_HOME:-./}" > /dev/null && printf '%s\n' "$PWD" ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

# ---- UnzipGit: self-heal for a missing / empty / corrupted gradle-wrapper.jar ----
# Symptom without this: "Could not find or load main class org.gradle.wrapper.GradleWrapperMain"
WRAPPER_JAR_FILE="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
WRAPPER_PROPS_FILE="$APP_HOME/gradle/wrapper/gradle-wrapper.properties"

jar_is_valid () {
    [ -f "$1" ] || return 1
    _size=$( wc -c < "$1" 2>/dev/null | tr -d ' ' )
    [ -n "$_size" ] && [ "$_size" -ge 10000 ] || return 1
    [ "$( head -c 2 "$1" 2>/dev/null )" = "PK" ] || return 1
    return 0
}

download_to () {
    # $1 = url, $2 = target file
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL --retry 3 -o "$2" "$1" 2>/dev/null && return 0
    fi
    if command -v wget >/dev/null 2>&1; then
        wget -q -O "$2" "$1" 2>/dev/null && return 0
    fi
    return 1
}

if ! jar_is_valid "$WRAPPER_JAR_FILE"; then
    warn "gradle-wrapper.jar отсутствует или повреждён — пробую скачать..."
    rm -f "$WRAPPER_JAR_FILE"
    mkdir -p "$APP_HOME/gradle/wrapper"
    for _url in \
        "https://raw.githubusercontent.com/gradle/gradle/v8.5.0/gradle/wrapper/gradle-wrapper.jar" \
        "https://github.com/gradle/gradle/raw/v8.5.0/gradle/wrapper/gradle-wrapper.jar"
    do
        download_to "$_url" "$WRAPPER_JAR_FILE.tmp" && jar_is_valid "$WRAPPER_JAR_FILE.tmp" \
            && mv -f "$WRAPPER_JAR_FILE.tmp" "$WRAPPER_JAR_FILE" && break
        rm -f "$WRAPPER_JAR_FILE.tmp"
    done
fi

if ! jar_is_valid "$WRAPPER_JAR_FILE"; then
    # Last resort: download the Gradle distribution itself and run it directly.
    _dist_url=$( sed -n 's/^distributionUrl=//p' "$WRAPPER_PROPS_FILE" 2>/dev/null | head -1 | sed 's/\\//g' )
    [ -n "$_dist_url" ] || _dist_url="https://services.gradle.org/distributions/gradle-8.5-bin.zip"
    _boot="${GRADLE_USER_HOME:-$HOME/.gradle}/unzipgit-bootstrap"
    _zip_name=${_dist_url##*/}
    _dir_name=${_zip_name%-bin.zip}
    _dir_name=${_dir_name%-all.zip}
    if [ ! -x "$_boot/$_dir_name/bin/gradle" ]; then
        mkdir -p "$_boot"
        warn "Скачиваю дистрибутив Gradle: $_dist_url"
        download_to "$_dist_url" "$_boot/$_zip_name" \
            && ( cd "$_boot" && unzip -q -o "$_zip_name" ) \
            && rm -f "$_boot/$_zip_name"
    fi
    if [ -x "$_boot/$_dir_name/bin/gradle" ]; then
        exec "$_boot/$_dir_name/bin/gradle" "$@"
    fi
    die "ERROR: gradle-wrapper.jar отсутствует, а скачать его не удалось (нет доступа в интернет?).
Положите рабочий gradle-wrapper.jar в gradle/wrapper/ или выполните: gradle wrapper --gradle-version 8.5"
fi
# ---- end self-heal ----

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --add-opens etc. for Java 9+ compatibility
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                             # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}                # looks like a POSIX filepath
                    [ -e "$t" ] ;;                        #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started,
        # but possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # unlike `shift`, we don't need to fear this fixed-length loop.
        eval "set -- $@ \"\$arg\""
        shift
    done
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them
#     in double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

exec "$JAVACMD" "$@"
